CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL
);

ALTER TABLE clients
ADD COLUMN x NUMERIC NOT NULL,
ADD COLUMN y NUMERIC NOT NULL;
